### ISSUE TITLE
pod errors in your dists

### ISSUE THREAD

**Issue by karenetheridge** [xenoterracide/Dist-Zilla-PluginBundle-Author-XENO#1]
I saw this go by in a few of your other recent releases too:

https://metacpan.org/source/XENO/Dist-Zilla-PluginBundle-Author-XENO-0.001006/README

**Comment by xenoterracide** [comment]
fantastic, looks like ReadmeFromPod is broken, or it's parsing before
weaver has processed it more likely... maybe i'll fix it... README files
aren't the biggest concern, since the pod actually works, and since this
stuff is basically in maint mode, and only getting updated because I had
cpantesters errors.

On Wed, Feb 11, 2015 at 11:39 AM, Karen Etheridge notifications@github.com
wrote:

> I saw this go by in a few of your other recent releases too:
> 
> https://metacpan.org/source/XENO/Dist-Zilla-PluginBundle-Author-XENO-0.001006/README
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/xenoterracide/Dist-Zilla-PluginBundle-Author-XENO/issues/1
> .

## 

Caleb Cushing

http://xenoterracide.com

Calendar:
https://www.google.com/calendar/embed?src=xenoterracide%40gmail.com&ctz=America/Chicago

**Comment by karenetheridge** [comment]
> it's parsing before weaver has processed it more likely

That would be my guess.  FWIW, I patched [ReadmeAnyFromPod] to specifically handle this problem, last year.

**Comment by xenoterracide** [comment]
urgh, is there for some reason that patches never make it into the original
distribution (could also argue about that fork of OurPkgVersion, which I
said I'd accept patches for the feature)... whatapita

On Wed, Feb 11, 2015 at 12:31 PM, Karen Etheridge notifications@github.com
wrote:

> it's parsing before weaver has processed it more likely
> 
> That would be my guess. FWIW, I patched [ReadmeAnyFromPod] to specifically
> handle this problem, last year.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/xenoterracide/Dist-Zilla-PluginBundle-Author-XENO/issues/1#issuecomment-73935949
> .

## 

Caleb Cushing

http://xenoterracide.com

Calendar:
https://www.google.com/calendar/embed?src=xenoterracide%40gmail.com&ctz=America/Chicago
